version: "3"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.0
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200
      - 9300:9300
  kibana:
    image: docker.elastic.co/kibana/kibana:7.6.0
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    links:
      - elasticsearch
  logstash:
    image: docker.elastic.co/logstash/logstash:7.6.0
    container_name: logstash
    volumes:
      - $PWD/logstash/config/:/usr/share/logstash/pipeline/
      - $PWD/logstash/log/:/home/
    ports:
      - "5044:5044"
      - "9600:9600"
    depends_on:
      - elasticsearch
    links:
      - elasticsearch
